package com.edw.mavenproject5.bean;
// Generated Dec 15, 2016 11:00:22 AM by Hibernate Tools 4.3.1

/**
 * Dosen generated by hbm2java (ini java bean)
 */
public class Dosen  implements java.io.Serializable {


     private String iddosen;
     private String namadosen;

     private String alamatdosen; //variable
    
     
    /**
     * @return the alamatdosen
     */
    public String getAlamatdosen() {
        return alamatdosen;
    }

    /**
     * @param alamatdosen the alamatdosen to set
     */
    public void setAlamatdosen(String alamatdosen) {
        this.alamatdosen = alamatdosen;
    }

    public Dosen() {
    }

    public Dosen(String iddosen, String namadosen) {
        this.iddosen = iddosen;
        this.namadosen = namadosen;
    }
    
    // methods getter + setter
    public String getIddosen() {
        return this.iddosen;
    }
    
    public void setIddosen(String iddosen) {
        this.iddosen = iddosen;
    }
    public String getNamadosen() {
        return this.namadosen;
    }
    
    public void setNamadosen(String namadosen) {
        this.namadosen = namadosen;
    }
}


